version: "3.8"

services:
  mobylab-app-db:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mobylab-app
      POSTGRES_DB: mobylab-app
      POSTGRES_PASSWORD: mobylab-app
    volumes:
      - mobylab-app-db-vol:/var/lib/postgresql/data

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    build:
      context: ./dotnetbackend-main/MobyLabWebProgramming.Backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mobylab-app-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=mobylab-app-db;Port=5432;Database=mobylab-app;Username=mobylab-app;Password=mobylab-app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

volumes:
  mobylab-app-db-vol:
